# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

[
  {
    "name": "Apple",
    "symbol": "AAPL",
    "price": 100,
    "image": "aapl.png"
  },
  {
    "name": "Microsoft",
    "symbol": "MSFT",
    "price": 100,
    "image": "msft.png"
  },
  {
    "name": "Amazon",
    "symbol": "AMZN",
    "price": 100,
    "image": "amzn.png"
  }
]

###

@assetId = {{ createAsset.response.body._id }}

###

GET  http://localhost:3000/assets

###

GET  http://localhost:3000/assets/{symbol}

###
# @name createWallet
POST http://localhost:3000/wallets

###
@walletId = {{ createWallet.response.body._id }}
GET  http://localhost:3000/wallets

###

GET  http://localhost:3000/wallets/{{ walletId }}

###
POST http://localhost:3000/wallets/{{ walletId }}/assets
Content-Type: application/json

{
  "assetId": "{{ assetId }}",
  "shares": 100
}